-- CreateTable
CREATE TABLE "_admin_user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "_admin_user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_admin_session" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "adminUserId" INTEGER NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastUsedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "_admin_session_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "_admin_user_email_key" ON "_admin_user"("email");

-- CreateIndex
CREATE UNIQUE INDEX "_admin_session_sessionToken_key" ON "_admin_session"("sessionToken");

-- AddForeignKey
ALTER TABLE "_admin_session" ADD CONSTRAINT "_admin_session_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "_admin_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
