/*
  Warnings:

  - You are about to drop the column `submitter_first_name` on the `submission` table. All the data in the column will be lost.
  - You are about to drop the column `submitter_last_name` on the `submission` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "submission" DROP COLUMN "submitter_first_name",
DROP COLUMN "submitter_last_name",
ADD COLUMN     "author" TEXT,
ADD COLUMN     "submitter_name" TEXT;

-- CreateTable
CREATE TABLE "resource_link" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "url" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "resource_link_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "submission_topic" (
    "submission_id" INTEGER NOT NULL,
    "topic_id" INTEGER NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "submission_topic_pkey" PRIMARY KEY ("submission_id","topic_id")
);

-- CreateTable
CREATE TABLE "submission_resource_link" (
    "submission_id" INTEGER NOT NULL,
    "resource_link_id" INTEGER NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "submission_resource_link_pkey" PRIMARY KEY ("submission_id","resource_link_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "resource_link_url_key" ON "resource_link"("url");

-- AddForeignKey
ALTER TABLE "submission_topic" ADD CONSTRAINT "submission_topic_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "submission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "submission_topic" ADD CONSTRAINT "submission_topic_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "topic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "submission_resource_link" ADD CONSTRAINT "submission_resource_link_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "submission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "submission_resource_link" ADD CONSTRAINT "submission_resource_link_resource_link_id_fkey" FOREIGN KEY ("resource_link_id") REFERENCES "resource_link"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
