-- CreateEnum
CREATE TYPE "SubmissionType" AS ENUM ('EVENT', 'ARTICLE');

-- CreateEnum
CREATE TYPE "SubmissionStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "EntityStatus" AS ENUM ('DRAFT', 'PUBLISHED');

-- CreateEnum
CREATE TYPE "ActionType" AS ENUM ('GUIDE', 'LINK', 'CONTACT', 'DONATE', 'VOLUNTEER');

-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('PROTEST', 'RALLY', 'VOLUNTEER', 'TOWN_HALL', 'WORKSHOP', 'MEETING');

-- CreateTable
CREATE TABLE "_topic" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "_topic_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_article" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "status" "EntityStatus" NOT NULL,
    "author" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "_article_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_action" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "actionType" "ActionType" NOT NULL,
    "status" "EntityStatus" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "_action_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_event" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "eventType" "EventType" NOT NULL,
    "status" "EntityStatus" NOT NULL,
    "startTime" TIMESTAMP(3) NOT NULL,
    "endTime" TIMESTAMP(3),
    "locationName" TEXT NOT NULL,
    "addressRaw" TEXT NOT NULL,
    "city" TEXT,
    "region" TEXT,
    "postalCode" TEXT,
    "country" TEXT,
    "latitude" DECIMAL(65,30),
    "longitude" DECIMAL(65,30),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "_event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_submission" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "submissionType" "SubmissionType" NOT NULL,
    "status" "SubmissionStatus" NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "submittedContent" TEXT NOT NULL,
    "eventType" "EventType",
    "startTime" TIMESTAMP(3),
    "endTime" TIMESTAMP(3),
    "locationName" TEXT,
    "addressRaw" TEXT,
    "city" TEXT,
    "region" TEXT,
    "postalCode" TEXT,
    "country" TEXT,
    "website" TEXT,
    "contactEmail" TEXT,
    "submitterFirstName" TEXT NOT NULL,
    "submitterLastName" TEXT NOT NULL,
    "submitterEmail" TEXT NOT NULL,
    "reviewNotes" TEXT,
    "articleId" INTEGER,
    "eventId" INTEGER,
    "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewedAt" TIMESTAMP(3),

    CONSTRAINT "_submission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_topic_article" (
    "topicId" INTEGER NOT NULL,
    "articleId" INTEGER NOT NULL,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedBy" TEXT NOT NULL,

    CONSTRAINT "_topic_article_pkey" PRIMARY KEY ("topicId","articleId")
);

-- CreateTable
CREATE TABLE "_topic_action" (
    "topicId" INTEGER NOT NULL,
    "actionId" INTEGER NOT NULL,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedBy" TEXT NOT NULL,

    CONSTRAINT "_topic_action_pkey" PRIMARY KEY ("topicId","actionId")
);

-- CreateTable
CREATE TABLE "_topic_event" (
    "topicId" INTEGER NOT NULL,
    "eventId" INTEGER NOT NULL,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedBy" TEXT NOT NULL,

    CONSTRAINT "_topic_event_pkey" PRIMARY KEY ("topicId","eventId")
);

-- CreateTable
CREATE TABLE "_article_action" (
    "articleId" INTEGER NOT NULL,
    "actionId" INTEGER NOT NULL,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedBy" TEXT NOT NULL,

    CONSTRAINT "_article_action_pkey" PRIMARY KEY ("articleId","actionId")
);

-- CreateTable
CREATE TABLE "_article_event" (
    "articleId" INTEGER NOT NULL,
    "eventId" INTEGER NOT NULL,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedBy" TEXT NOT NULL,

    CONSTRAINT "_article_event_pkey" PRIMARY KEY ("articleId","eventId")
);

-- CreateTable
CREATE TABLE "_action_event" (
    "actionId" INTEGER NOT NULL,
    "eventId" INTEGER NOT NULL,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedBy" TEXT NOT NULL,

    CONSTRAINT "_action_event_pkey" PRIMARY KEY ("actionId","eventId")
);

-- CreateIndex
CREATE UNIQUE INDEX "_topic_slug_key" ON "_topic"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "_article_slug_key" ON "_article"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "_action_slug_key" ON "_action"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "_submission_articleId_key" ON "_submission"("articleId");

-- CreateIndex
CREATE UNIQUE INDEX "_submission_eventId_key" ON "_submission"("eventId");

-- AddForeignKey
ALTER TABLE "_submission" ADD CONSTRAINT "_submission_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "_article"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_submission" ADD CONSTRAINT "_submission_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "_event"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_topic_article" ADD CONSTRAINT "_topic_article_topicId_fkey" FOREIGN KEY ("topicId") REFERENCES "_topic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_topic_article" ADD CONSTRAINT "_topic_article_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "_article"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_topic_action" ADD CONSTRAINT "_topic_action_topicId_fkey" FOREIGN KEY ("topicId") REFERENCES "_topic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_topic_action" ADD CONSTRAINT "_topic_action_actionId_fkey" FOREIGN KEY ("actionId") REFERENCES "_action"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_topic_event" ADD CONSTRAINT "_topic_event_topicId_fkey" FOREIGN KEY ("topicId") REFERENCES "_topic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_topic_event" ADD CONSTRAINT "_topic_event_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "_event"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_article_action" ADD CONSTRAINT "_article_action_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "_article"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_article_action" ADD CONSTRAINT "_article_action_actionId_fkey" FOREIGN KEY ("actionId") REFERENCES "_action"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_article_event" ADD CONSTRAINT "_article_event_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "_article"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_article_event" ADD CONSTRAINT "_article_event_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "_event"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_action_event" ADD CONSTRAINT "_action_event_actionId_fkey" FOREIGN KEY ("actionId") REFERENCES "_action"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_action_event" ADD CONSTRAINT "_action_event_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "_event"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "_submission"
ADD CONSTRAINT submission_one_of_target_chk
CHECK (
  -- never both
  NOT ("articleId" IS NOT NULL AND "eventId" IS NOT NULL)
  AND
  -- approved must have exactly one target
  (
    status <> 'APPROVED'
    OR num_nonnulls("articleId", "eventId") = 1
  )
);