-- CreateEnum
CREATE TYPE submission_type AS ENUM ('EVENT', 'ARTICLE');

-- CreateEnum
CREATE TYPE submission_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE entity_status AS ENUM ('DRAFT', 'PUBLISHED');

-- CreateEnum
CREATE TYPE action_type AS ENUM ('GUIDE', 'LINK', 'CONTACT', 'DONATE', 'VOLUNTEER');

-- CreateEnum
CREATE TYPE event_type AS ENUM ('PROTEST', 'RALLY', 'VOLUNTEER', 'TOWN_HALL', 'WORKSHOP', 'MEETING');

-- CreateTable
CREATE TABLE "topic" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "topic_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "article" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "status" entity_status NOT NULL,
    "author" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "published_at" TIMESTAMP(3) NOT NULL,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "article_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "action" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "action_type" action_type NOT NULL,
    "status" entity_status NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "action_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "website" TEXT,
    "contact_email" TEXT,
    "event_type" event_type NOT NULL,
    "status" entity_status NOT NULL,
    "start_time" TIMESTAMP(3) NOT NULL,
    "end_time" TIMESTAMP(3),
    "location_name" TEXT NOT NULL,
    "public_location_description" TEXT,
    "address_line1" TEXT,
    "address_line2" TEXT,
    "city" TEXT,
    "region" TEXT,
    "postal_code" TEXT,
    "country" TEXT,
    "latitude" DECIMAL(65,30),
    "longitude" DECIMAL(65,30),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "submission" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "submission_type" submission_type NOT NULL,
    "status" submission_status NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "submitted_content" TEXT NOT NULL,
    "event_type" event_type,
    "start_time" TIMESTAMP(3),
    "end_time" TIMESTAMP(3),
    "location_name" TEXT,
    "public_location_description" TEXT,
    "address_line1" TEXT,
    "address_line2" TEXT,
    "city" TEXT,
    "region" TEXT,
    "postal_code" TEXT,
    "country" TEXT,
    "website" TEXT,
    "contact_email" TEXT,
    "submitter_first_name" TEXT NOT NULL,
    "submitter_last_name" TEXT NOT NULL,
    "submitter_email" TEXT NOT NULL,
    "review_notes" TEXT,
    "article_id" INTEGER,
    "event_id" INTEGER,
    "submitted_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewed_at" TIMESTAMP(3),

    CONSTRAINT "submission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "topic_article" (
    "topic_id" INTEGER NOT NULL,
    "article_id" INTEGER NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" TEXT NOT NULL,

    CONSTRAINT "topic_article_pkey" PRIMARY KEY ("topic_id","article_id")
);

-- CreateTable
CREATE TABLE "topic_action" (
    "topic_id" INTEGER NOT NULL,
    "action_id" INTEGER NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" TEXT NOT NULL,

    CONSTRAINT "topic_action_pkey" PRIMARY KEY ("topic_id","action_id")
);

-- CreateTable
CREATE TABLE "topic_event" (
    "topic_id" INTEGER NOT NULL,
    "event_id" INTEGER NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" TEXT NOT NULL,

    CONSTRAINT "topic_event_pkey" PRIMARY KEY ("topic_id","event_id")
);

-- CreateTable
CREATE TABLE "article_action" (
    "article_id" INTEGER NOT NULL,
    "action_id" INTEGER NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" TEXT NOT NULL,

    CONSTRAINT "article_action_pkey" PRIMARY KEY ("article_id","action_id")
);

-- CreateTable
CREATE TABLE "article_event" (
    "article_id" INTEGER NOT NULL,
    "event_id" INTEGER NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" TEXT NOT NULL,

    CONSTRAINT "article_event_pkey" PRIMARY KEY ("article_id","event_id")
);

-- CreateTable
CREATE TABLE "action_event" (
    "action_id" INTEGER NOT NULL,
    "event_id" INTEGER NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" TEXT NOT NULL,

    CONSTRAINT "action_event_pkey" PRIMARY KEY ("action_id","event_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "topic_slug_key" ON "topic"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "article_slug_key" ON "article"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "action_slug_key" ON "action"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "submission_article_id_key" ON "submission"("article_id");

-- CreateIndex
CREATE UNIQUE INDEX "submission_event_id_key" ON "submission"("event_id");

-- AddForeignKey
ALTER TABLE "submission" ADD CONSTRAINT "submission_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "article"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "submission" ADD CONSTRAINT "submission_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "topic_article" ADD CONSTRAINT "topic_article_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "topic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "topic_article" ADD CONSTRAINT "topic_article_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "article"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "topic_action" ADD CONSTRAINT "topic_action_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "topic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "topic_action" ADD CONSTRAINT "topic_action_action_id_fkey" FOREIGN KEY ("action_id") REFERENCES "action"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "topic_event" ADD CONSTRAINT "topic_event_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "topic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "topic_event" ADD CONSTRAINT "topic_event_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "article_action" ADD CONSTRAINT "article_action_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "article"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "article_action" ADD CONSTRAINT "article_action_action_id_fkey" FOREIGN KEY ("action_id") REFERENCES "action"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "article_event" ADD CONSTRAINT "article_event_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "article"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "article_event" ADD CONSTRAINT "article_event_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "action_event" ADD CONSTRAINT "action_event_action_id_fkey" FOREIGN KEY ("action_id") REFERENCES "action"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "action_event" ADD CONSTRAINT "action_event_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "submission"
ADD CONSTRAINT submission_one_of_target_check
CHECK (
  -- never both
  NOT ("article_id" IS NOT NULL AND "event_id" IS NOT NULL)
  AND
  -- approved must have exactly one target
  (
    status <> 'APPROVED'
    OR num_nonnulls("article_id", "event_id") = 1
  )
);
