name: ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Monorepo lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Monorepo typecheck
        run: pnpm typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Monorepo build
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        run: pnpm build

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Web unit test
        run: pnpm --filter web test

      - name: API unit test
        run: pnpm --filter api test:unit

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: API Integration test
        run: pnpm --filter api test:integration

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Install Playwright Chromium
        run: pnpm --filter api exec playwright install --with-deps chromium

      - name: E2E test
        run: pnpm --filter api test:e2e

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Dependency audit
        run: pnpm audit --prod
