name: ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Monorepo
        run: pnpm install

      - name: Monorepo lint
        continue-on-error: true
        run: pnpm lint

      - name: Monorepo typecheck
        continue-on-error: true
        run: pnpm typecheck

      - name: Monorepo build
        run: pnpm build

      - name: Monorepo test
        run: pnpm test